---
- name: Update API Server certificate
  kubernetes.core.k8s:
    template:
      - secret.yaml.j2
      - api_server/api_certs.yaml.j2
  vars:
    _secret_name: "{{ ocp_cluster_config_api_certificate.secret_name }}"
    _secret_namespace: openshift-config
    _secrets:
      tls.crt: "{{ ocp_cluster_config_api_certificate.crt }}"
      tls.key: "{{ ocp_cluster_config_api_certificate.key }}"
    _secret_type: kubernetes.io/tls
