---
- template: 
    src: cluster_role/cluster_role.yaml.j2
    dest: "/tmp/{{ role.name }}.yml"
  loop: "{{ ocp_cluster_config_cluster_roles }}"
  loop_control:
    loop_var: role

- name: Create cluster roles rule
  kubernetes.core.k8s:
    template: cluster_role/cluster_role.yaml.j2
  loop: "{{ ocp_cluster_config_cluster_roles }}"
  loop_control:
    loop_var: role

- name: Bind Cluster role
  kubernetes.core.k8s:
    template: cluster_role/cluster_role_binding.yaml.j2
  loop: "{{ ocp_cluster_config_cluster_role_binding }}"
  loop_control:
    loop_var: role_binding
