---

- name: Update Console URL
  kubernetes.core.k8s:
    definition:
      apiVersion: config.openshift.io/v1
      kind: Ingress
      metadata:
        name: cluster
      spec:
        componentRoutes:
          - name: console
            namespace: openshift-console
            hostname: "{{ ocp_cluster_config_console.url }}"
    merge_type:
      - merge
  when: ocp_cluster_config_console.url | d(false)
