---
- name: Generate IDP secret
  kubernetes.core.k8s:
    definition:
      kind: Secret
      metadata:
        name: "idp-{{ idp.name }}-secret"
        namespace: openshift-config
      data:
        clientSecret: "{{ idp.secret | b64encode }}"
  loop: ocp_cluster_config_idp
  loop_control:
    loop_var: idp

- name: Set IDP
  kubernetes.core.k8s:
    definition:
      kind: OAuth
      apiVersion: config.openshift.io/v1
      metadata:
        name: cluster
      spec:
        identityProviders:
          - name: "{{ idp.name }}"
            mappingMethod: claim
            type: OpenID
            openID:
              clientID: "{{ idp.client_id }}"
              clientSecret:
                name: "idp-{{ idp.name }}-secret"
              claims:
                email:
                  - email
                id:
                  - sub
                name:
                  - name
                preferredUsername:
                  - preferred_username
              issuer: "{{ idp.issuer }}"
    merge_type:
      - merge
  loop: ocp_cluster_config_idp
  loop_control:
    loop_var: idp
