---
- name:
  set_facts:
    _hosts: "{{ groups[_group_name] }}"

- name:
  set_facts:    
    _taints: "{{ hostvars[_hosts[0]].ocp_cluster_config_infra_node_taints }}"
    
- name: Set infra nodes label
  kubernetes.core.k8s:
    template: node/set_infra_node.yaml.j2
  loop: "{{ _hosts }}"
  loop_control:
    loop_var: _node_name
