---

- name: Identity Providers Configuration
  ansible.builtin.include_tasks: idp.yml
  when: ocp_cluster_config_idp

- name: Proxy Configuration
  ansible.builtin.include_tasks: proxy.yml
  when: ocp_cluster_config_proxy

- name: Cluster role Configuration
  ansible.builtin.include_tasks: cluster_roles.yml
  when: ocp_cluster_config_cluster_roles

- name: Cluster role binding Configuration
  ansible.builtin.include_tasks: cluster_role_binding.yml
  when: ocp_cluster_config_cluster_role_binding

- name: API Certificate
  ansible.builtin.include_tasks: api_certificate.yml
  when: ocp_cluster_config_api_certificate

- name: Console Config
  ansible.builtin.include_tasks: console.yml
  when: ocp_cluster_config_console

- name: Ingress Controller Config
  ansible.builtin.include_tasks: ingress_controller.yml
  when: ocp_cluster_config_ingress_controller
