---

- name: Identity Providers Configuration
  ansible.builtin.include_tasks: idp.yml
  when: ocp_cluster_config_idp

- name: Proxy Configuration
  ansible.builtin.include_tasks: proxy.yml
  when: ocp_cluster_config_proxy

- name: Cluster role Configuration
  ansible.builtin.include_tasks: cluster_roles.yml

- name: API Certificate
  ansible.builtin.include_tasks: api_certificate.yml
  when: ocp_cluster_config_api_certificate

- name: Console Config
  ansible.builtin.include_tasks: console.yml

- name: Ingress Controller Config
  ansible.builtin.include_tasks: ingress_controller.yml
  when: ocp_cluster_config_ingress_controller

- name: Infra node Config
  ansible.builtin.include_tasks: infra-node.yml

- name: Monitoring Config
  ansible.builtin.include_tasks: monitor.yml

- name: ETCD config
  ansible.builtin.include_tasks: etcd.yml

- name: Webconsole Style
  ansible.builtin.include_tasks: webconsole.yml

- name: Hardening config
  ansible.builtin.include_tasks: hardening.yml

- name: Tuning
  ansible.builtin.include_tasks: tuning.yml
  when: ocp_cluster_config_add_custom_kubeconfig_mcp
