---

- name: Identity Providers Configuration
  ansible.builtin.include_tasks: idp.yml
  when: ocp_cluster_config_idp_openid

- name: Proxy Configuration
  ansible.builtin.include_tasks: proxy.yml
  when: ocp_cluster_config_proxy

- name: Cluster role Configuration
  ansible.builtin.include_tasks: cluster_roles.yml

- name: API Certificate
  ansible.builtin.include_tasks: api_certificate.yml
  when: ocp_cluster_config_api_certificate is defined

- name: Console Config
  ansible.builtin.include_tasks: console.yml

- name: Ingress Controller Config
  ansible.builtin.include_tasks: ingress_controller.yml
  when: ocp_cluster_config_ingress_controller is defined

- name: Infra node Config
  ansible.builtin.include_tasks: infra-node.yml
  loop: "{{ ocp_cluster_config_infra_groups }}"
  loop_control:
    loop_var: _group_name

- name: Monitoring Config
  ansible.builtin.include_tasks: monitor.yml

- name: ETCD config
  ansible.builtin.include_tasks: etcd.yml

- name: Webconsole Style
  ansible.builtin.include_tasks: webconsole.yml

- name: Global customization
  ansible.builtin.include_tasks: customization.yml

- name: Hardening config
  ansible.builtin.include_tasks: hardening.yml

- name: Tuning
  ansible.builtin.include_tasks: tuning.yml
  when: ocp_cluster_config_add_custom_kubeconfig_mcp

- name: MachineConfig for kerberos
  ansible.builtin.include_tasks: kerberos.yml
