---

- name: Configure Proxy
  kubernetes.core.k8s:
    definition:
      apiVersion: config.openshift.io/v1
      kind: Proxy
      metadata:
        name: cluster
      spec:
        httpProxy: "{{ ocp_cluster_config_proxy.http_proxy }}"
        httpsProxy: "{{ ocp_cluster_config_proxy.https_proxy }}"
        noProxy: "{{ ocp_cluster_config_proxy.no_proxy }}"
