---
- name: Get custom logo
  ansible.builtin.slurp:
    src: "{{ ocp_cluster_config_webconsole_logo_path }}"
  register: _logo
  when: ocp_cluster_config_webconsole_logo_path

- name: Get custom login logo
  ansible.builtin.slurp:
    src: "{{ ocp_cluster_config_webconsole_login_logo_path | default(ocp_cluster_config_webconsole_logo_path) }}"
  register: _login_logo

- name: Set Console Custom logo
  kubernetes.core.k8s:
    template:
      - console/configmap-custom_logo.yaml.j2
  vars:
    logo_b64_data: "{{ _logo.content }}"
  when: _logo | d(false)

- name: Set Custom Login logo
  kubernetes.core.k8s:
    template:
      - console/custom_logo.yaml.j2
  when: _logo | d(false)

- name: Set Console Custom login page as secret
  kubernetes.core.k8s:
    template: secret.yaml.j2
  vars:
    login_logo_b64_data: "{{ _login_logo.content }}"
    _secret_name: "custom-login-page-secret"
    _secret_namespace: openshift-config
    _secret_type: Opaque
    _secrets:
      providers.html: "{{ lookup('template','console/custom-providers-rh-template.html.j2', variable_start_string='[%', variable_end_string='%]', block_start_string='[[%', block_end_string='%]]') }}"
  when: _login_logo | d(false)     

- name: Patch oauth config
  kubernetes.core.k8s:
    template: console/custom_provider_page.yaml.j2
  when: _login_logo | d(false)

- name: Modify session timeout
  kubernetes.core.k8s:
    template: console/custom_console_session_timeout.yaml.j2
  when: ocp_cluster_config_console_session_timeout | d(false)
  loop: "{{ ocp_cluster_config_session_timeout_targets }}"
  loop_control:
    loop_var: session
  
- name: Create special route for custom favicon
  kubernetes.core.k8s:
    template: console/custom_favicon.yaml.j2
  when: ocp_cluster_config_webconsole_favicon | d(false)

- name: Create export control banner
  kubernetes.core.k8s:
    template: console/custom_console_notification.yaml.j2
  when: ocp_cluster_config_console_notification | d(false)
