---
- name: Get custom logo
  ansible.builtin.slurp:
    src: "{{ ocp_cluster_config_webconsole_logo_path }}"
  register: _logo
  when: ocp_cluster_config_webconsole_logo_path

- name: Set Console Custom logo
  kubernetes.core.k8s:
    template:
      - console/confirmap-custom_logo.yaml.j2
      - console/custom_logo.yaml.j2
  when: _logo | d(false)

- name: Create special route for custom favicon
  kubernetes.core.k8s:
    template: console/custom_favicon.yaml.j2
  when: ocp_cluster_config_webconsole_favicon | d(false)

- name: Create export control banner
  kubernetes.core.k8s:
    template: console/custom_console_notification.yaml.j2
  when: ocp_cluster_config_console_notification | d(false)
